commands/game/convert.js
commands/narrator/srole.js

Fixes https://github.com/wwosimulation/tracker/issues/121

Test for bug #121

---

commands/game/give.js

Fixes https://github.com/wwosimulation/tracker/issues/125

Bug #125 fix

---

commands/narrator/day.js
commands/narrator/srole.js

Fixes https://github.com/wwosimulation/tracker/issues/118

#sect-member upgrades

---

commands/bot/botinfo.js
commands/bot/roleinfo.js
commands/bot/serverinfo.js
commands/economy/daily.js
commands/economy/inventory.js
commands/economy/profile.js
commands/narrator/day.js
commands/narrator/gwhost.js
commands/narrator/night.js
commands/narrator/playerinfo.js
commands/narrator/srole.js
commands/narrator/win.js
commands/staff/quest.js
events/guildMemberUpdate.js

Fixes https://github.com/wwosimulation/tracker/issues/131
Updates all embeds i know of to v13

Fixes #131

---

commands/economy/balance.js
commands/game/forge.js
commands/narrator/day.js
commands/narrator/manual.js

- Fixes https://github.com/wwosimulation/tracker/issues/67
- Fixes https://github.com/wwosimulation/tracker/issues/102
- Fixes https://github.com/wwosimulation/tracker/issues/107
- Fixes https://github.com/wwosimulation/tracker/issues/129

Fixes #129 #107 #102 and #67

---

.github/workflows/nb.yml
commands/bot/serverinfo.js
commands/economy/cmi.js
commands/economy/shop.js
commands/economy/use.js
commands/game/watch.js
commands/narrator/day.js
commands/narrator/gwhost.js
commands/narrator/joingame.js
commands/narrator/night.js
commands/narrator/nmanual.js
commands/narrator/playerinfo.js
commands/narrator/rwhost.js
commands/narrator/say.js
commands/narrator/vt.js
events/button.js
events/dropdown.js
events/guildMemberUpdate.js
server.js

Fixes https://github.com/wwosimulation/tracker/issues/144
Fixes https://github.com/wwosimulation/tracker/issues/141
Closes https://github.com/wwosimulation/tracker/issues/92

Mega bug patch time

---

commands/narrator/night.js

Closes wwosimulation/tracker#149

Fixes  #149

---

commands/narrator/vt.js

Closes wwosimulation/tracker#160

Fixed vt command

---

commands/bot/help.js

Added how to play, economy, fun and bot
Fixes https://github.com/wwosimulation/tracker/issues/56

implement help command (tracker#56)

---

commands/game/hack.js
commands/game/mute.js
commands/narrator/day.js
commands/narrator/hackkill.js
commands/narrator/night.js
commands/narrator/reset.js
commands/narrator/vt.js
server.js

Closes wwosimulation/tracker#153 and wwosimulation/tracker#159

Hacker Role

---

commands/narrator/night.js
commands/narrator/srole.js

Closes wwosimulation/tracker#88
Closes wwosimulation/tracker#171

Minor Bug fix

---

commands/game/hack.js

Closes wwosimulation/tracker#172
Closes wwosimulation/tracker#175

Should fix role not defined

---

commands/game/hack.js

This reverts commit 4412c232d47a0f4ee24f2f4067bf8bbf65bc9754.

Revert "Update hack.js (#88)"

---

commands/game/trap.js
commands/game/watch.js
commands/narrator/day.js
commands/narrator/night.js
commands/narrator/srole.js

Fixes wwosimulation/tracker#173
Fixes wwosimulation/tracker#158
Fixes wwosimulation/tracker#165
Should fix wwosimulation/tracker#81
Should fix wwosimulation/tracker#176

Mega Bug fix

---

commands/narrator/cancel.js
commands/narrator/gwhost.js

Cancel fix

---

commands/bot/bug.js
commands/bot/reloadconfig.js
commands/bot/roleinfo.js
commands/bot/suggest.js
commands/bot/timer.js
commands/dev/botowner.js
commands/dev/eval.js
commands/economy/buy.js
commands/economy/colorchange.js
commands/economy/namechange.js
commands/economy/profile.js
commands/economy/shop.js
commands/staff/am.js
commands/staff/massping.js
commands/staff/oldcmi.js
commands/staff/quest.js
commands/staff/rm.js
commands/staff/stafflist.js
commands/staff/updatexp.js
commands/staff/xp.js

bot, dev, economy, fun, staff is done. [tracker#151](https://github.com/wwosimulation/tracker/issues/151)
game and narrator is in process.

Update error responses and removed some unnecessary code

---

commands/economy/buy.js
commands/game/bomb.js
commands/game/corrupt.js
commands/game/eat.js
commands/game/poison.js
commands/game/shoot.js
commands/game/stab.js
commands/game/water.js
commands/narrator/manual.js
commands/narrator/night.js
commands/narrator/nmanual.js
commands/narrator/win.js
commands/staff/xp.js

Closes wwosimulation/tracker#195
Closes wwosimulation/tracker#194
Closes wwosimulation/tracker#63
Closes wwosimulation/tracker#29
and I think that is all
~~wwosimulation/tracker#41~~
~~wwosimulation/tracker#38~~
wwosimulation/tracker#168

Bug fixes (lots)

---

commands/bot/bug.js
commands/bot/settings.js
commands/bot/suggest.js
commands/bot/timer.js
commands/economy/colorchange.js
commands/economy/daily.js
commands/economy/namechange.js
commands/economy/use.js
commands/game/bomb.js
commands/game/check.js
commands/game/convert.js
commands/game/copy.js
commands/game/mute.js
commands/staff/oldcmi.js

Error responses set 2

---

commands/bot/bug.js
commands/bot/suggest.js
server.js

Temporary until I can generate new credentials for GitHub (which is a massive headache to do)

Disable GitHub

---

events/messageCreate.js
package.json
server.js

This will eventually replace #error-logs

Add Sentry logging

---

commands/economy/leaderboard.js
server.js

<h1>Leaderboard command</h1>
<h3>Features</h3>
1. Leaderboard for gems, coins, xp and roses.
2. Switch between pages using the paginator.
<h3>Usage</h3>
`+lb 2 coins` Page 2 of Coin-lb
`+lb roses` Page 1 of Rose-lb
closes wwosimulation/tracker#45
~~_No tests ran on beta_~~
✔️ All tests successfully passed

Leaderboard

---

commands/narrator/srole.js

Fixes https://github.com/wwosimulation/tracker/issues/253

Exclusions

---

commands/game/convert.js
commands/narrator/day.js

Closes https://github.com/wwosimulation/tracker/issues/260
Closes https://github.com/wwosimulation/tracker/issues/257
Closes https://github.com/wwosimulation/tracker/issues/251
Closes https://github.com/wwosimulation/tracker/issues/249

Fixes #260, #257, #251 and #249

---

commands/game/water.js

Fixes wwosimulation/tracker#338

Priest fix

---

commands/staff/player.js
slashCommands/staffSlash/playerSlash.js

Fixes wwosimulation/tracker#353

Player commandfix

---

commands/economy/profile.js
package.json

This will allow the new hosting to work for now, while I try to figure out why canvas is being stupid and won't install on an arm64 machine properly

Disable canvas

---

commands/narrator/night.js
commands/narrator/startgame.js

Fixes https://github.com/wwosimulation/tracker/issues/340

FINALLY FIXES STUPUD BUG

---

events/stafflist.js

Fixes https://github.com/wwosimulation/tracker/issues/395

Add Event Hosts to the Staff List

---

commands/bot/badges.js
commands/bot/botinfo.js
commands/bot/help.js
commands/bot/roleinfo.js
commands/dev/gamepanel.js
commands/dev/nuke.js
commands/economy/daily.js
commands/economy/inventory.js
commands/economy/leaderboard.js
commands/economy/profile.js
commands/economy/rosewheel.js
commands/economy/shop.js
commands/fun/emoji.js
commands/fun/write.js
commands/narrator/gwhost.js
commands/narrator/playerinfo.js
commands/narrator/rwhost.js
commands/narrator/win.js
commands/staff/quest.js

Puts most of the MessageEmbed object into the constructor. Would check to make sure it works though with beta bot.

Embed Deprication Update

---

commands/economy/colorchange.js

Suggested by yologuy in the server

Add British Aliases

---

commands/bot/settings.js

Fixes https://github.com/wwosimulation/tracker/issues/380

Language alias

---

commands/narrator/day.js

Fixes https://github.com/wwosimulation/tracker/issues/396

Hacker hacked

---

commands/game/bomb.js
commands/game/hack.js
commands/game/hypnotize.js
commands/game/revive.js
commands/narrator/hackkill.js
commands/narrator/progpeace.js
commands/narrator/progterror.js

fixes https://github.com/wwosimulation/tracker/issues/451
fixes https://github.com/wwosimulation/tracker/issues/450
fixes https://github.com/wwosimulation/tracker/issues/449
fixes https://github.com/wwosimulation/tracker/issues/443
fixes https://github.com/wwosimulation/tracker/issues/441
fixes https://github.com/wwosimulation/tracker/issues/414
fixes https://github.com/wwosimulation/tracker/issues/409
fixes https://github.com/wwosimulation/tracker/issues/387
fixes https://github.com/wwosimulation/tracker/issues/385
fixes https://github.com/wwosimulation/tracker/issues/374
fixes https://github.com/wwosimulation/tracker/issues/362
fixes https://github.com/wwosimulation/tracker/issues/229
fixes https://github.com/wwosimulation/tracker/issues/162

Updated help

---

commands/narrator/startgame.js

- delete the database every time a game starts

Kitten Wolf

---

commands/narrator/day.js

- possible fix for villager dying after being converted from kww revenge
- possible fix for zombie not dying after 3 days

Kitten wolf and zombie

---

commands/game/visit.js

- fixed a bug where the red lady could not visit at night

Fix Red Lady

---

commands/narrator/playerinfo.js
events/messageCreate.js

Adds two new options to the playerinfo command:
`+playerinfo` - Sends the fancy embed
`+playerinfo raw` - Sends just the message
`+playerinfo block` - Sends just the message in a code block
Closes https://github.com/wwosimulation/tracker/issues/473

Player info

---

commands/staff/disablebuttons.js
commands/staff/endtest.js

closes https://github.com/wwosimulation/tracker/issues/487
fixes https://github.com/wwosimulation/tracker/issues/490

button clearing

---

commands/game/flee.js
commands/narrator/kill.js

closes wwosimulation/tracker#492

Update and rename suicide.js to flee.js

---

server.js
slashCommands/staffSlash/lotterySlash.js

closes https://github.com/wwosimulation/tracker/issues/482

lottery embed with usernames

---

commands/economy/buy.js

closes https://github.com/wwosimulation/tracker/issues/496

no beta buy

---

commands/narrator/vt.js

I made an oopsie when I was changing the files to use objects

Changed the class method to an array method

---

commands/game/trap.js
commands/narrator/win.js
events/messageCreate.js
server.js
slashCommands/staffSlash/lotterySlash.js

fixes https://github.com/wwosimulation/tracker/issues/438

Small changes/fixes

---

commands/game/trap.js
commands/narrator/win.js
events/messageCreate.js
server.js
slashCommands/staffSlash/lotterySlash.js

Reverts wwosimulation/Narrator-bot#329

Revert "Small changes/fixes"

---

commands/bot/badges.js
events/autocomplete.js

closes https://github.com/wwosimulation/tracker/issues/497

Badges Help

---

commands/game/flee.js
commands/narrator/day/others/sheriffs.js
commands/narrator/day/others/spiritseers.js
commands/narrator/killall.js
commands/narrator/manual.js
commands/narrator/nmanual.js
commands/narrator/startgame.js
commands/narrator/win.js

More patches because it works perfectly during testing and loves to break during production even if it's the same code.

Patches v2

---

commands/dev/reloadslash.js
commands/game/terror.js
commands/narrator/disable.js
commands/narrator/enable.js
commands/narrator/manual.js
commands/narrator/night/others/channels.js
commands/narrator/startgame.js
commands/narrator/unlock.js
events/modals.js
package.json
server.js
slashCommands/botSlash/bugSlash.js
slashCommands/botSlash/suggestSlash.js
slashCommands/botSlash/suggestionSlash.js

f65a5ed2433c50c0e6017bb8710f5403fb66de18 fixes https://github.com/wwosimulation/tracker/issues/333
46e122d9c93d66016f977043d48ea44941b4a8bd closes https://github.com/wwosimulation/tracker/issues/370
71a1edce5e7d7edd3df9cf025c4f72d8467e9da8 closes https://github.com/wwosimulation/tracker/issues/535
8090eb23a9599f3b9be198a450ca967490c29248 closes https://github.com/wwosimulation/tracker/issues/543
077734f658e4849a480b304f7b670a413f9fd0f4 fixes https://github.com/wwosimulation/tracker/issues/541

Closing Issues
